### PR TITLE
accents: unify all accents & make them cleaner

### PR DESCRIPTION
**Pull request by MASTERGUY**
Signed-off-by: MASTERGUY <murtipipo@gmail.com>

### CODE REVIEW

**Comment by poad42** [comment]
Did you test this? because changing sting attr will break things.

**Comment by MASTERGUY** [comment]
> Did you test this? because changing sting attr will break things.

check our other themes i just modified those to follow same as our other themes and yes it is tested :) for sanity i will clean flash and report back

**Comment by MASTERGUY** [comment]
> > Did you test this? because changing sting attr will break things.
> 
> check our other themes i just modified those to follow same as our other themes and yes it is tested :) for sanity i will clean flash and report back

sorry made a derp after i tested it xD it is fine now will tested :)

**Review by gotenksIN — COMMENTED** [review]
I think we can live by without `LOCAL_SRC_FILES := $(call all-subdir-java-files)`
apart from that looks good to me

**Comment by idoybh** [comment]
Say the word and we can merge @gotenksIN

**Comment by poad42** [comment]
@MASTERGUY doesn't wanna merge yet. I'll wait on his word.

**Comment by idoybh** [comment]
Than whoever feels like merging merge. Seems fine to me

**Comment by idoybh** [comment]
Thank you @MASTERGUY

**Pull request merged**
